[package]
name = "crustr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.rust-analyzer]
rustc_private=true 

[dependencies]
crustr_passes = { path = "../core/crustr_passes" }
compiler_interface = { path = "../core/compiler_interface" }
log = "0.4"
env_logger = "0.9"
toml_edit = "0.13.0"
clap = { version = "3.0.10", features = ["derive"] }