[workspace]
members = [ "crates/analyses",
    "crates/utils",
    "crates/preprocess",
]

[package]
name = "crown"
version = "0.1.0"
edition = "2024"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
utils = { path = "crates/utils" }
analyses = { path = "crates/analyses" }
preprocess = { path = "crates/preprocess" }
