[workspace]
members = [
    "orc-common",
    "orc-preprocess",
    "orc-ownership-analysis",
    "utvpi",
    "orc-taint-analysis",
    "orc-refactor",
    "usage-analysis",
    "refactor",
    "empirical-study",
    "ownership-analysis"
]

[package]
name = "orc"
version = "0.0.1"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
orc-common = { path = "orc-common" }
orc-preprocess = { path = "orc-preprocess" }
orc-ownership-analysis = { path = "orc-ownership-analysis" }
ownership-analysis = { path = "ownership-analysis" }
orc-taint-analysis = { path = "orc-taint-analysis" }
usage-analysis = { path = "usage-analysis" }
refactor = { path = "refactor" }
empirical-study = { path = "empirical-study" }
clap = { version = "3.1.2", features = ["derive"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["env-filter"] }
anyhow = "1.0"
# jemallocator = "0.5"
