[workspace]
members = [
    "core/compiler_interface",
    "core/analysis",
    "core/rewriter",
    "core/refactor",
    "core/utils/graph",
    "core/utils/range_ext",
]

[package]
name = "orc"
version = "0.0.1"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
clap = { version = "3.1.2", features = ["derive"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.10"
analysis = { path = "core/analysis" }
refactor = { path = "core/refactor" }
rewriter = { path = "core/rewriter" }
