[workspace]
members = [
    "core",
    "utils/graph_ext",
]

[package]
name = "orc"
version = "0.0.1"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
clap = { version = "3.1.2", features = ["derive"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.10"
core = { path = "core" }
