[workspace]

members = [
    "src/bin",
    "refactorer/compiler_interface",
    "refactorer/crustr_analysis",
    "refactorer/crustr_rustc_interface",
    "refactorer/crustr_rewrite",
    "refactorer/crustr_passes",
    "utils/graph",
]
