[workspace]

members = [
    "bin",
    "refactorer/compiler_interface",
    "refactorer/crustr_analysis",
    "refactorer/crustr_rustc_interface",
    "refactorer/crustr_rewrite",
    "refactorer/crustr_passes",
    "refactorer/utils/graph",
]
