[workspace]
members = [ "crates/analyses",
    "crates/utils",
    "crates/preprocess",
]

[package]
name = "crown"
version = "0.1.0"
edition = "2024"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
utils = { path = "crates/utils" }
analyses = { path = "crates/analyses" }
preprocess = { path = "crates/preprocess" }
refactor = { path = "crates/refactor" }
clap = { version = "4.5.42", features = ["derive"] }

[build-dependencies]
c2rust-bitfields = "0.20.0"
c2rust-bitfields-derive = "0.20.0"