[workspace]

members = [
    "src/bin",
    "refactorer/pointer_analysis",
    "refactorer/crustr_mir_passes",
    "refactorer/crustr_rustc_interface",
    "utils/graph",
    "utils/index",
    "rustfix",
]
