[workspace]
members = [
    "core/compiler_interface",
    "core/analysis",
    "core/rewrite",
    "core/refactor",
    "core/utils/graph",
]

[package]
name = "crustr"
version = "0.0.1"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
clap = { version = "3.1.2", features = ["derive"] }
env_logger = "0.9"
analysis = { path = "core/analysis" }
refactor = { path = "core/refactor" }
