[workspace]
members = [
    "analysis-interface",
    "ownership-analysis",
    "usage-analysis",
    "refactor",
    "empirical-study",
]

[package]
name = "orc"
version = "0.0.1"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
analysis-interface = { path = "analysis-interface" }
ownership-analysis = { path = "ownership-analysis" }
usage-analysis = { path = "usage-analysis" }
refactor = { path = "refactor" }

clap = { version = "3.1.2", features = ["derive"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["env-filter"] }
