[workspace]

members = [
    "src/bin",
    "refactorer/crustr_analysis",
    "refactorer/crustr_rustc_interface",
    "refactorer/crustr_rewrite",
    "utils/graph",
    "utils/index",
    "utils/work_list",
    #"instrumented_rustc_borrowck"
]
