[workspace]

members = [
    "src/curr",
    "refactorer/pointer_analysis",
    "refactorer/transform",
    "refactorer/compiler_interface",
    "utils/graph",
    "utils/index",
    "rustfix",
    "destructive_readable",
]
