[workspace]

members = [
    "bin",
    "core/compiler_interface",
    "core/crustr_analysis",
    "core/crustr_rustc_interface",
    "core/crustr_rewrite",
    "core/crustr_passes",
    "core/utils/graph",
]
