[package]
name = "usage-analysis"
authors = ["Rose Hudson <rose@krx.sh>"]
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
orc-common = { path = "../orc-common" }
tracing = "0.1.32"
smallvec = "1.9.0"
