.TH ZCMPI 3 libzahl
.SH NAME
zcmpi - Compare a big integer and a signed integer
.SH SYNOPSIS
.nf
#include <zahl.h>

int zcmpi(z_t \fIa\fP, signed long long int \fIb\fP);
.fi
.SH DESCRIPTION
.B zcmpi
compares
.I a
and
.IR b .
.SH RETURN VALUE
.B zcmpi
returns -1 if
.I a
is less than
.IR b ,
0 if
.I a
is equal to
.IR b ,
and +1 if
.I a
is greater than
.IR b .
.SH SEE ALSO
.BR zcmp (3),
.BR zcmpu (3),
.BR zcmpmag (3)
