.TH ZCMPU 3 libzahl
.SH NAME
zcmpu - Compare a big integer and an unsigned integer
.SH SYNOPSIS
.nf
#include <zahl.h>

int zcmpu(z_t \fIa\fP, unsigned long long int \fIb\fP);
.fi
.SH DESCRIPTION
.B zcmpu
compares
.I a
and
.IR b .
.SH RETURN VALUE
.B zcmpu
returns -1 if
.I a
is less than
.IR b ,
0 if
.I a
is equal to
.IR b ,
and +1 if
.I a
is greater than
.IR b .
.SH SEE ALSO
.BR zcmp (3),
.BR zcmpi (3),
.BR zcmpmag (3)
