.TH ZDIV 3 libzahl
.SH NAME
zdiv - Calculate the quotient of two big integer
.SH SYNOPSIS
.nf
#include <zahl.h>

void zdiv(z_t \fIquotient\fP, z_t \fIdividend\fP, z_t \fIdivisor\fP);
.fi
.SH DESCRIPTION
.B zdiv
calculates the truncated quotient of a
.I dividend
and a
.IR divisor ,
and stores the result in
.IR quotient .
That is,
.I quotient
gets
.I dividend
/
.IR divisor .
.P
It is safe to call
.B zdiv
with non-unique parameters.
.SH SEE ALSO
.BR zdivmod (3),
.BR zstr (3),
.BR zadd (3),
.BR zsub (3),
.BR zmul (3),
.BR zmod (3),
.BR zneg (3),
.BR zabs (3),
.BR zpow (3)
