[package]
name = "analyses"
version = "0.1.0"
edition = "2024"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
utils = { path = "../utils" }
smallvec = { version = "1.15.1", features = ["union", "const_generics"] }

[dev-dependencies]
utils = { path = "../utils", features = ["test-utils"] }
