[package]
name = "utvpi"
version = "0.1.0"
edition = "2021"
description = "implementation of a UTVPI solver"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
