[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
anyhow = "1.0.98"
itertools = "0.14.0"
petgraph = "0.8.2"
rustc-hash = "2.1.1"
similar = "2.7.0"
smallvec = { version = "1.15.1", features = ["union", "const_generics", "const_new", "arbitrary", "specialization", "serde"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter"] }
ctor = { version = "0.4.2", optional = true }
either = "1.15.0"


[features]
test-utils = ["dep:ctor"]
