[package]
name = "crustr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.rust-analyzer]
rustc_private=true 

[dependencies]
crustr_rustc_interface = { path = "../../refactorer/crustr_rustc_interface" }
log = "0.4"
env_logger = "0.9"
toml = "0.5.8"
clap = { version = "3.0.10", features = ["derive"] }