[package]
name = "rustc_borrowck"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[package.metadata.rust-analyzer]
rustc_private=true 


[dependencies]
either = "1.5.0"
itertools = "0.9"
tracing = "0.1"
smallvec = { version = "1.6.1", features = ["union", "may_dangle"] }
