[workspace]
members = [
]
[package]
name = "libtree-rs"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[lib]
name = "libtree"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[dependencies]
libc= "0.2"
